version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-master
    user: root
    ports:
      - "8080:8080"      # Jenkins web interface
      - "50000:50000"    # Jenkins agent communication
    volumes:
      - jenkins_home:/var/jenkins_home           # Jenkins data storage
      - /var/run/docker.sock:/var/run/docker.sock # Docker access
      - ./workspace:/workspace                    # Build workspace
    environment:
      - JENKINS_OPTS=--httpPort=8080
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    restart: unless-stopped

volumes:
  jenkins_home:
    driver: local